### ISSUE TITLE
Using the "Add Member" button in the GUI throws error

### ISSUE THREAD

**Issue by benlmyers** [BradBouquio/LandClaim#2] opened 2021-06-20 21:21 UTC
Players have reported issues with adding members to their land claims.

When they click the "Add Members to Claim" icon (the Totem) in the /lc GUI, nothing happens.

In the console, an error is thrown:

```
[21:16:50 ERROR]: Could not pass event InventoryClickEvent to LandClaim v2.0.1
java.lang.NullPointerException: null
        at net.minespire.landclaim.GUI.NGUI.open(NGUI.java:32) ~[?:?]
        at net.minespire.landclaim.GUI.GUIManager.openAddPlayer(GUIManager.java:197) ~[?:?]
        at net.minespire.landclaim.Listener.GUIClick.onInventoryClick(GUIClick.java:109) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor323.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-576]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-576]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-576]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2687) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-576]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

Any fix/help would be appreciated!

**Comment by BradBouquio** [comment] 2021-08-29 03:10
I believe this may be caused by colors or tags being used in the player's display name. Should be an easy fix by using the getName method instead. I will test this and see how it goes.

**Comment by BradBouquio** [comment] 2021-08-29 03:39
I cannot reproduce the issue but I believe the issue should be resolved with the latest update.

**Closed as completed by BradBouquio** 2021-08-29 03:39 UTC

**Comment by benlmyers** [comment] 2021-08-30 23:02
Sounds good. Thanks, Brad!
